parameters:
    pspid: ~
    environment: ~
    sha_in: ~
    sha_out: ~
    options: ~

services:
    snowcap_ogone:
        class: Snowcap\OgoneBundle\Manager
        arguments: [@event_dispatcher, @logger, @snowcap_ogone.form_generator, %pspid%, %environment%, %sha_in%, %sha_out%, %options%]

    snowcap_ogone.form_generator:
        class: Snowcap\OgoneBundle\FormGenerator\SimpleFormGenerator
        arguments: [@twig, %kernel.root_dir%]
        private: true